https://www.hackerrank.com/challenges/bookmarks
https://www.hackerrank.com/challenges/s10-basic-statistics
https://www.hackerrank.com/challenges/s10-binomial-distribution-1
https://www.hackerrank.com/challenges/s10-binomial-distribution-2
https://www.hackerrank.com/challenges/s10-geometric-distribution-1
https://www.hackerrank.com/challenges/s10-geometric-distribution-2
https://www.hackerrank.com/challenges/s10-interquartile-range
https://www.hackerrank.com/challenges/s10-least-square-regression-line
https://www.hackerrank.com/challenges/s10-mcq-1
https://www.hackerrank.com/challenges/s10-mcq-2
https://www.hackerrank.com/challenges/s10-mcq-3
https://www.hackerrank.com/challenges/s10-mcq-4
https://www.hackerrank.com/challenges/s10-mcq-5
https://www.hackerrank.com/challenges/s10-mcq-6
https://www.hackerrank.com/challenges/s10-mcq-7
https://www.hackerrank.com/challenges/s10-multiple-linear-regression
https://www.hackerrank.com/challenges/s10-normal-distribution-1
https://www.hackerrank.com/challenges/s10-normal-distribution-2
https://www.hackerrank.com/challenges/s10-pearson-correlation-coefficient
https://www.hackerrank.com/challenges/s10-poisson-distribution-1
https://www.hackerrank.com/challenges/s10-poisson-distribution-2
https://www.hackerrank.com/challenges/s10-quartiles
https://www.hackerrank.com/challenges/s10-spearman-rank-correlation-coefficient
https://www.hackerrank.com/challenges/s10-standard-deviation
https://www.hackerrank.com/challenges/s10-the-central-limit-theorem-1
https://www.hackerrank.com/challenges/s10-the-central-limit-theorem-2
https://www.hackerrank.com/challenges/s10-the-central-limit-theorem-3
https://www.hackerrank.com/challenges/s10-weighted-mean
