https://www.hackerrank.com/challenges/alien-username
https://www.hackerrank.com/challenges/alternative-matching
https://www.hackerrank.com/challenges/backreferences-to-failed-groups
https://www.hackerrank.com/challenges/bookmarks
https://www.hackerrank.com/challenges/branch-reset-groups
https://www.hackerrank.com/challenges/capturing-non-capturing-groups
https://www.hackerrank.com/challenges/detect-html-links
https://www.hackerrank.com/challenges/detect-html-tags
https://www.hackerrank.com/challenges/detecting-valid-latitude-and-longitude
https://www.hackerrank.com/challenges/detect-the-domain-name
https://www.hackerrank.com/challenges/detect-the-email-addresses
https://www.hackerrank.com/challenges/excluding-specific-characters
https://www.hackerrank.com/challenges/find-a-word
https://www.hackerrank.com/challenges/find-hackerrank
https://www.hackerrank.com/challenges/find-substring
https://www.hackerrank.com/challenges/forward-references
https://www.hackerrank.com/challenges/hackerrank-language
https://www.hackerrank.com/challenges/hackerrank-tweets
https://www.hackerrank.com/challenges/html-attributes
https://www.hackerrank.com/challenges/ide-identifying-comments
https://www.hackerrank.com/challenges/ip-address-validation
https://www.hackerrank.com/challenges/matching-anything-but-new-line
https://www.hackerrank.com/challenges/matching-digits-non-digit-character
https://www.hackerrank.com/challenges/matching-ending-items
https://www.hackerrank.com/challenges/matching-one-or-more-repititions
https://www.hackerrank.com/challenges/matching-range-of-characters
https://www.hackerrank.com/challenges/matching-same-text-again-again
https://www.hackerrank.com/challenges/matching-specific-characters
https://www.hackerrank.com/challenges/matching-specific-string
https://www.hackerrank.com/challenges/matching-start-end
https://www.hackerrank.com/challenges/matching-whitespace-non-whitespace-character
https://www.hackerrank.com/challenges/matching-word-boundaries
https://www.hackerrank.com/challenges/matching-word-non-word
https://www.hackerrank.com/challenges/matching-x-repetitions
https://www.hackerrank.com/challenges/matching-x-y-repetitions
https://www.hackerrank.com/challenges/matching-zero-or-more-repetitions
https://www.hackerrank.com/challenges/negative-lookahead
https://www.hackerrank.com/challenges/negative-lookbehind
https://www.hackerrank.com/challenges/positive-lookahead
https://www.hackerrank.com/challenges/positive-lookbehind
https://www.hackerrank.com/challenges/programming-language-detection
https://www.hackerrank.com/challenges/saying-hi
https://www.hackerrank.com/challenges/split-number
https://www.hackerrank.com/challenges/stack-exchange-scraper
https://www.hackerrank.com/challenges/uk-and-us
https://www.hackerrank.com/challenges/uk-and-us-2
https://www.hackerrank.com/challenges/utopian-identification-number
https://www.hackerrank.com/challenges/valid-pan-format
