https://www.hackerrank.com/challenges/amazons-10
https://www.hackerrank.com/challenges/antichess
https://www.hackerrank.com/challenges/arimaa
https://www.hackerrank.com/challenges/a-text-processing-warmup
https://www.hackerrank.com/challenges/backgammon
https://www.hackerrank.com/challenges/basic-probability-puzzles-1
https://www.hackerrank.com/challenges/basic-probability-puzzles-10
https://www.hackerrank.com/challenges/basic-probability-puzzles-2
https://www.hackerrank.com/challenges/basic-probability-puzzles-3
https://www.hackerrank.com/challenges/basic-probability-puzzles-4
https://www.hackerrank.com/challenges/basic-probability-puzzles-5
https://www.hackerrank.com/challenges/basic-probability-puzzles-6
https://www.hackerrank.com/challenges/basic-probability-puzzles-7
https://www.hackerrank.com/challenges/basic-probability-puzzles-8
https://www.hackerrank.com/challenges/basic-probability-puzzles-9
https://www.hackerrank.com/challenges/basic-spell-checker
https://www.hackerrank.com/challenges/battery
https://www.hackerrank.com/challenges/battleship
https://www.hackerrank.com/challenges/battleship1p
https://www.hackerrank.com/challenges/biddingtictactoe
https://www.hackerrank.com/challenges/bookmarks
https://www.hackerrank.com/challenges/botclean
https://www.hackerrank.com/challenges/botcleanlarge
https://www.hackerrank.com/challenges/botcleanr
https://www.hackerrank.com/challenges/botcleanv2
https://www.hackerrank.com/challenges/byte-the-correct-apple
https://www.hackerrank.com/challenges/camelot
https://www.hackerrank.com/challenges/checkers
https://www.hackerrank.com/challenges/click-o-mania
https://www.hackerrank.com/challenges/computing-the-correlation
https://www.hackerrank.com/challenges/conway
https://www.hackerrank.com/challenges/copsrobber
https://www.hackerrank.com/challenges/correct-the-search-query
https://www.hackerrank.com/challenges/correlation-and-regression-lines-1
https://www.hackerrank.com/challenges/correlation-and-regression-lines-2
https://www.hackerrank.com/challenges/correlation-and-regression-lines-3
https://www.hackerrank.com/challenges/correlation-and-regression-lines-4
https://www.hackerrank.com/challenges/correlation-and-regression-lines-5
https://www.hackerrank.com/challenges/correlation-and-regression-lines-6
https://www.hackerrank.com/challenges/correlation-and-regression-lines-7
https://www.hackerrank.com/challenges/correlation-and-regression-lines-8
https://www.hackerrank.com/challenges/count-the-balls
https://www.hackerrank.com/challenges/count-the-circles
https://www.hackerrank.com/challenges/count-the-faces
https://www.hackerrank.com/challenges/count-the-pairs-of-tracks
https://www.hackerrank.com/challenges/craigslist-post-classifier-the-category
https://www.hackerrank.com/challenges/digital-camera-day-or-night
https://www.hackerrank.com/challenges/dip-image-segmentation-1
https://www.hackerrank.com/challenges/dip-image-segmentation-2
https://www.hackerrank.com/challenges/dip-image-thresholding
https://www.hackerrank.com/challenges/dip-morphological-operations-closing
https://www.hackerrank.com/challenges/dip-morphological-operations-dilation
https://www.hackerrank.com/challenges/dip-morphological-operations-dilation-with-an-irregular-structuring-element
https://www.hackerrank.com/challenges/dip-morphological-operations-erosion
https://www.hackerrank.com/challenges/dip-morphological-operations-erosion-with-a-structuring-element
https://www.hackerrank.com/challenges/dip-morphological-operations-opening
https://www.hackerrank.com/challenges/dip-popular-convolution-filters-1
https://www.hackerrank.com/challenges/dip-popular-convolution-filters-2
https://www.hackerrank.com/challenges/dip-popular-convolution-filters-3
https://www.hackerrank.com/challenges/dip-popular-convolution-filters-4
https://www.hackerrank.com/challenges/disambiguation-mouse-vs-mouse
https://www.hackerrank.com/challenges/document-classification
https://www.hackerrank.com/challenges/domineering
https://www.hackerrank.com/challenges/dota2prediction
https://www.hackerrank.com/challenges/expand-the-acronyms
https://www.hackerrank.com/challenges/forecasting-passenger-traffic
https://www.hackerrank.com/challenges/from-paragraphs-to-sentences
https://www.hackerrank.com/challenges/gomoku
https://www.hackerrank.com/challenges/guess-the-flipkart-query
https://www.hackerrank.com/challenges/heros-and-heroines-villains-and-villainesses
https://www.hackerrank.com/challenges/hex
https://www.hackerrank.com/challenges/hip
https://www.hackerrank.com/challenges/image-upsampling
https://www.hackerrank.com/challenges/kamisado
https://www.hackerrank.com/challenges/language-detection
https://www.hackerrank.com/challenges/lightsout
https://www.hackerrank.com/challenges/mancala6
https://www.hackerrank.com/challenges/markov-snakes-and-ladders
https://www.hackerrank.com/challenges/matching-book-names-and-descriptions
https://www.hackerrank.com/challenges/matching-questions-answers
https://www.hackerrank.com/challenges/maze-escape
https://www.hackerrank.com/challenges/missing-stock-prices
https://www.hackerrank.com/challenges/morrisnine
https://www.hackerrank.com/challenges/nlp-compute-the-cross-entropy
https://www.hackerrank.com/challenges/nlp-compute-the-perplexity
https://www.hackerrank.com/challenges/nlp-pos-tagging
https://www.hackerrank.com/challenges/nlp-pos-tagging-2
https://www.hackerrank.com/challenges/nlp-similarity-scores
https://www.hackerrank.com/challenges/n-puzzle
https://www.hackerrank.com/challenges/oracle1
https://www.hackerrank.com/challenges/oracle2
https://www.hackerrank.com/challenges/oracle3
https://www.hackerrank.com/challenges/oracle4
https://www.hackerrank.com/challenges/oracle5
https://www.hackerrank.com/challenges/pacman-astar
https://www.hackerrank.com/challenges/pacman-bfs
https://www.hackerrank.com/challenges/pacman-dfs
https://www.hackerrank.com/challenges/pacman-ucs
https://www.hackerrank.com/challenges/peg-solitaire
https://www.hackerrank.com/challenges/pipelayer
https://www.hackerrank.com/challenges/places-or-faces
https://www.hackerrank.com/challenges/poisson-distribution-1
https://www.hackerrank.com/challenges/poisson-distribution-2
https://www.hackerrank.com/challenges/poisson-distribution-3
https://www.hackerrank.com/challenges/poisson-distribution-5
https://www.hackerrank.com/challenges/predicting-house-prices
https://www.hackerrank.com/challenges/predicting-office-space-price
https://www.hackerrank.com/challenges/predict-missing-grade
https://www.hackerrank.com/challenges/punctuation-corrector-its
https://www.hackerrank.com/challenges/quarto
https://www.hackerrank.com/challenges/quora-answer-classifier
https://www.hackerrank.com/challenges/reversi
https://www.hackerrank.com/challenges/saveprincess
https://www.hackerrank.com/challenges/saveprincess2
https://www.hackerrank.com/challenges/segment-the-twitter-hashtags
https://www.hackerrank.com/challenges/senet
https://www.hackerrank.com/challenges/shakespeare-cuts-it-short
https://www.hackerrank.com/challenges/shape-detection
https://www.hackerrank.com/challenges/stack-exchange-question-classifier
https://www.hackerrank.com/challenges/standard-deviation-puzzles-1
https://www.hackerrank.com/challenges/standard-deviation-puzzles-2
https://www.hackerrank.com/challenges/standard-deviation-puzzles-3
https://www.hackerrank.com/challenges/standard-deviation-puzzles-4
https://www.hackerrank.com/challenges/standard-deviation-puzzles-5
https://www.hackerrank.com/challenges/standard-deviation-puzzles-6
https://www.hackerrank.com/challenges/stat-warmup
https://www.hackerrank.com/challenges/stitch-the-torn-wiki
https://www.hackerrank.com/challenges/stockprediction
https://www.hackerrank.com/challenges/t9-predictions
https://www.hackerrank.com/challenges/temperature-predictions
https://www.hackerrank.com/challenges/the-best-aptitude-test
https://www.hackerrank.com/challenges/the-bidding-game
https://www.hackerrank.com/challenges/the-captcha-cracker
https://www.hackerrank.com/challenges/the-central-limit-theorem-1
https://www.hackerrank.com/challenges/the-central-limit-theorem-2
https://www.hackerrank.com/challenges/the-central-limit-theorem-3
https://www.hackerrank.com/challenges/the-central-limit-theorem-4
https://www.hackerrank.com/challenges/the-central-limit-theorem-5
https://www.hackerrank.com/challenges/the-central-limit-theorem-6
https://www.hackerrank.com/challenges/the-missing-apostrophes
https://www.hackerrank.com/challenges/the-missing-characters
https://www.hackerrank.com/challenges/the-rubix-cube
https://www.hackerrank.com/challenges/the-super-captcha-cracker
https://www.hackerrank.com/challenges/the-trigram
https://www.hackerrank.com/challenges/tic-tac-toe
https://www.hackerrank.com/challenges/time-series-prediction
https://www.hackerrank.com/challenges/to-be-what
https://www.hackerrank.com/challenges/tron
https://www.hackerrank.com/challenges/tronv2
https://www.hackerrank.com/challenges/url-hashtag-segmentation
https://www.hackerrank.com/challenges/who-is-it
