https://www.hackerrank.com/challenges/15-days-of-learning-sql
https://www.hackerrank.com/challenges/african-cities
https://www.hackerrank.com/challenges/asian-population
https://www.hackerrank.com/challenges/average-population
https://www.hackerrank.com/challenges/average-population-of-each-continent
https://www.hackerrank.com/challenges/binary-search-tree-1
https://www.hackerrank.com/challenges/bookmarks
https://www.hackerrank.com/challenges/challenges
https://www.hackerrank.com/challenges/contest-leaderboard
https://www.hackerrank.com/challenges/draw-the-triangle-1
https://www.hackerrank.com/challenges/draw-the-triangle-2
https://www.hackerrank.com/challenges/earnings-of-employees
https://www.hackerrank.com/challenges/full-score
https://www.hackerrank.com/challenges/harry-potter-and-wands
https://www.hackerrank.com/challenges/interviews
https://www.hackerrank.com/challenges/japanese-cities-attributes
https://www.hackerrank.com/challenges/japanese-cities-name
https://www.hackerrank.com/challenges/japan-population
https://www.hackerrank.com/challenges/more-than-75-marks
https://www.hackerrank.com/challenges/name-of-employees
https://www.hackerrank.com/challenges/occupations
https://www.hackerrank.com/challenges/placements
https://www.hackerrank.com/challenges/population-density-difference
https://www.hackerrank.com/challenges/print-prime-numbers
https://www.hackerrank.com/challenges/revising-aggregations-sum
https://www.hackerrank.com/challenges/revising-aggregations-the-average-function
https://www.hackerrank.com/challenges/revising-aggregations-the-count-function
https://www.hackerrank.com/challenges/revising-the-select-query
https://www.hackerrank.com/challenges/revising-the-select-query-2
https://www.hackerrank.com/challenges/salary-of-employees
https://www.hackerrank.com/challenges/select-all-sql
https://www.hackerrank.com/challenges/select-by-id
https://www.hackerrank.com/challenges/sql-projects
https://www.hackerrank.com/challenges/symmetric-pairs
https://www.hackerrank.com/challenges/the-blunder
https://www.hackerrank.com/challenges/the-company
https://www.hackerrank.com/challenges/the-pads
https://www.hackerrank.com/challenges/the-report
https://www.hackerrank.com/challenges/weather-observation-station-1
https://www.hackerrank.com/challenges/weather-observation-station-10
https://www.hackerrank.com/challenges/weather-observation-station-11
https://www.hackerrank.com/challenges/weather-observation-station-12
https://www.hackerrank.com/challenges/weather-observation-station-13
https://www.hackerrank.com/challenges/weather-observation-station-14
https://www.hackerrank.com/challenges/weather-observation-station-15
https://www.hackerrank.com/challenges/weather-observation-station-16
https://www.hackerrank.com/challenges/weather-observation-station-17
https://www.hackerrank.com/challenges/weather-observation-station-18
https://www.hackerrank.com/challenges/weather-observation-station-19
https://www.hackerrank.com/challenges/weather-observation-station-2
https://www.hackerrank.com/challenges/weather-observation-station-20
https://www.hackerrank.com/challenges/weather-observation-station-3
https://www.hackerrank.com/challenges/weather-observation-station-4
https://www.hackerrank.com/challenges/weather-observation-station-5
https://www.hackerrank.com/challenges/weather-observation-station-6
https://www.hackerrank.com/challenges/weather-observation-station-7
https://www.hackerrank.com/challenges/weather-observation-station-8
https://www.hackerrank.com/challenges/weather-observation-station-9
https://www.hackerrank.com/challenges/what-type-of-triangle
