https://www.hackerrank.com/challenges/bookmarks
https://www.hackerrank.com/challenges/can-you-access
https://www.hackerrank.com/challenges/duplicate-word
https://www.hackerrank.com/challenges/java-1d-array
https://www.hackerrank.com/challenges/java-1d-array-introduction
https://www.hackerrank.com/challenges/java-2d-array
https://www.hackerrank.com/challenges/java-abstract-class
https://www.hackerrank.com/challenges/java-anagrams
https://www.hackerrank.com/challenges/java-annotations
https://www.hackerrank.com/challenges/java-arraylist
https://www.hackerrank.com/challenges/java-bigdecimal
https://www.hackerrank.com/challenges/java-biginteger
https://www.hackerrank.com/challenges/java-bitset
https://www.hackerrank.com/challenges/java-comparator
https://www.hackerrank.com/challenges/java-covariance
https://www.hackerrank.com/challenges/java-currency-formatter
https://www.hackerrank.com/challenges/java-datatypes
https://www.hackerrank.com/challenges/java-date-and-time
https://www.hackerrank.com/challenges/java-dequeue
https://www.hackerrank.com/challenges/java-end-of-file
https://www.hackerrank.com/challenges/java-exception-handling
https://www.hackerrank.com/challenges/java-exception-handling-try-catch
https://www.hackerrank.com/challenges/java-factory
https://www.hackerrank.com/challenges/java-generics
https://www.hackerrank.com/challenges/java-hashset
https://www.hackerrank.com/challenges/java-if-else
https://www.hackerrank.com/challenges/java-inheritance-1
https://www.hackerrank.com/challenges/java-inheritance-2
https://www.hackerrank.com/challenges/java-instanceof-keyword
https://www.hackerrank.com/challenges/java-interface
https://www.hackerrank.com/challenges/java-int-to-string
https://www.hackerrank.com/challenges/java-iterator
https://www.hackerrank.com/challenges/java-lambda-expressions
https://www.hackerrank.com/challenges/java-list
https://www.hackerrank.com/challenges/java-loops
https://www.hackerrank.com/challenges/java-loops-i
https://www.hackerrank.com/challenges/java-md5
https://www.hackerrank.com/challenges/java-method-overriding
https://www.hackerrank.com/challenges/java-method-overriding-2-super-keyword
https://www.hackerrank.com/challenges/java-negative-subarray
https://www.hackerrank.com/challenges/java-output-formatting
https://www.hackerrank.com/challenges/java-primality-test
https://www.hackerrank.com/challenges/java-priority-queue
https://www.hackerrank.com/challenges/java-reflection-attributes
https://www.hackerrank.com/challenges/java-regex
https://www.hackerrank.com/challenges/java-singleton
https://www.hackerrank.com/challenges/java-sort
https://www.hackerrank.com/challenges/java-stack
https://www.hackerrank.com/challenges/java-static-initializer-block
https://www.hackerrank.com/challenges/java-stdin-and-stdout-1
https://www.hackerrank.com/challenges/java-stdin-stdout
https://www.hackerrank.com/challenges/java-string-compare
https://www.hackerrank.com/challenges/java-string-reverse
https://www.hackerrank.com/challenges/java-strings-introduction
https://www.hackerrank.com/challenges/java-string-tokens
https://www.hackerrank.com/challenges/java-substring
https://www.hackerrank.com/challenges/java-vistor-pattern
https://www.hackerrank.com/challenges/pattern-syntax-checker
https://www.hackerrank.com/challenges/phone-book
https://www.hackerrank.com/challenges/prime-checker
https://www.hackerrank.com/challenges/sha-256
https://www.hackerrank.com/challenges/simple-addition-varargs
https://www.hackerrank.com/challenges/tag-content-extractor
https://www.hackerrank.com/challenges/valid-username-checker
https://www.hackerrank.com/challenges/welcome-to-java
