https://www.hackerrank.com/challenges/alphabet-rangoli
https://www.hackerrank.com/challenges/any-or-all
https://www.hackerrank.com/challenges/bookmarks
https://www.hackerrank.com/challenges/calendar-module
https://www.hackerrank.com/challenges/capitalize
https://www.hackerrank.com/challenges/class-1-dealing-with-complex-numbers
https://www.hackerrank.com/challenges/class-2-find-the-torsional-angle
https://www.hackerrank.com/challenges/collections-counter
https://www.hackerrank.com/challenges/compress-the-string
https://www.hackerrank.com/challenges/decorators-2-name-directory
https://www.hackerrank.com/challenges/default-arguments
https://www.hackerrank.com/challenges/defaultdict-tutorial
https://www.hackerrank.com/challenges/designer-door-mat
https://www.hackerrank.com/challenges/detect-html-tags-attributes-and-attribute-values
https://www.hackerrank.com/challenges/exceptions
https://www.hackerrank.com/challenges/find-angle
https://www.hackerrank.com/challenges/find-a-string
https://www.hackerrank.com/challenges/finding-the-percentage
https://www.hackerrank.com/challenges/find-second-maximum-number-in-a-list
https://www.hackerrank.com/challenges/floor-ceil-and-rint
https://www.hackerrank.com/challenges/ginorts
https://www.hackerrank.com/challenges/hex-color-code
https://www.hackerrank.com/challenges/html-parser-part-1
https://www.hackerrank.com/challenges/html-parser-part-2
https://www.hackerrank.com/challenges/incorrect-regex
https://www.hackerrank.com/challenges/input
https://www.hackerrank.com/challenges/introduction-to-regex
https://www.hackerrank.com/challenges/iterables-and-iterators
https://www.hackerrank.com/challenges/itertools-combinations
https://www.hackerrank.com/challenges/itertools-combinations-with-replacement
https://www.hackerrank.com/challenges/itertools-permutations
https://www.hackerrank.com/challenges/itertools-product
https://www.hackerrank.com/challenges/list-comprehensions
https://www.hackerrank.com/challenges/map-and-lambda-expression
https://www.hackerrank.com/challenges/matrix-script
https://www.hackerrank.com/challenges/maximize-it
https://www.hackerrank.com/challenges/merge-the-tools
https://www.hackerrank.com/challenges/most-commons
https://www.hackerrank.com/challenges/nested-list
https://www.hackerrank.com/challenges/no-idea
https://www.hackerrank.com/challenges/np-array-mathematics
https://www.hackerrank.com/challenges/np-arrays
https://www.hackerrank.com/challenges/np-concatenate
https://www.hackerrank.com/challenges/np-dot-and-cross
https://www.hackerrank.com/challenges/np-eye-and-identity
https://www.hackerrank.com/challenges/np-inner-and-outer
https://www.hackerrank.com/challenges/np-linear-algebra
https://www.hackerrank.com/challenges/np-mean-var-and-std
https://www.hackerrank.com/challenges/np-min-and-max
https://www.hackerrank.com/challenges/np-polynomials
https://www.hackerrank.com/challenges/np-shape-reshape
https://www.hackerrank.com/challenges/np-sum-and-prod
https://www.hackerrank.com/challenges/np-transpose-and-flatten
https://www.hackerrank.com/challenges/np-zeros-and-ones
https://www.hackerrank.com/challenges/piling-up
https://www.hackerrank.com/challenges/polar-coordinates
https://www.hackerrank.com/challenges/py-check-strict-superset
https://www.hackerrank.com/challenges/py-check-subset
https://www.hackerrank.com/challenges/py-collections-deque
https://www.hackerrank.com/challenges/py-collections-namedtuple
https://www.hackerrank.com/challenges/py-collections-ordereddict
https://www.hackerrank.com/challenges/py-hello-world
https://www.hackerrank.com/challenges/py-if-else
https://www.hackerrank.com/challenges/py-introduction-to-sets
https://www.hackerrank.com/challenges/py-set-add
https://www.hackerrank.com/challenges/py-set-difference-operation
https://www.hackerrank.com/challenges/py-set-discard-remove-pop
https://www.hackerrank.com/challenges/py-set-intersection-operation
https://www.hackerrank.com/challenges/py-set-mutations
https://www.hackerrank.com/challenges/py-set-symmetric-difference-operation
https://www.hackerrank.com/challenges/py-set-union
https://www.hackerrank.com/challenges/py-the-captains-room
https://www.hackerrank.com/challenges/python-arithmetic-operators
https://www.hackerrank.com/challenges/python-division
https://www.hackerrank.com/challenges/python-eval
https://www.hackerrank.com/challenges/python-integers-come-in-all-sizes
https://www.hackerrank.com/challenges/python-lists
https://www.hackerrank.com/challenges/python-loops
https://www.hackerrank.com/challenges/python-mod-divmod
https://www.hackerrank.com/challenges/python-mutations
https://www.hackerrank.com/challenges/python-power-mod-power
https://www.hackerrank.com/challenges/python-print
https://www.hackerrank.com/challenges/python-quest-1
https://www.hackerrank.com/challenges/python-sort-sort
https://www.hackerrank.com/challenges/python-string-formatting
https://www.hackerrank.com/challenges/python-string-split-and-join
https://www.hackerrank.com/challenges/python-time-delta
https://www.hackerrank.com/challenges/python-tuples
https://www.hackerrank.com/challenges/reduce-function
https://www.hackerrank.com/challenges/re-findall-re-finditer
https://www.hackerrank.com/challenges/re-group-groups
https://www.hackerrank.com/challenges/re-split
https://www.hackerrank.com/challenges/re-start-re-end
https://www.hackerrank.com/challenges/re-sub-regex-substitution
https://www.hackerrank.com/challenges/standardize-mobile-number-using-decorators
https://www.hackerrank.com/challenges/string-validators
https://www.hackerrank.com/challenges/swap-case
https://www.hackerrank.com/challenges/symmetric-difference
https://www.hackerrank.com/challenges/text-alignment
https://www.hackerrank.com/challenges/text-wrap
https://www.hackerrank.com/challenges/the-minion-game
https://www.hackerrank.com/challenges/triangle-quest-2
https://www.hackerrank.com/challenges/validate-a-roman-number
https://www.hackerrank.com/challenges/validate-list-of-email-address-with-filter
https://www.hackerrank.com/challenges/validating-credit-card-number
https://www.hackerrank.com/challenges/validating-named-email-addresses
https://www.hackerrank.com/challenges/validating-postalcode
https://www.hackerrank.com/challenges/validating-the-phone-number
https://www.hackerrank.com/challenges/validating-uid
https://www.hackerrank.com/challenges/whats-your-name
https://www.hackerrank.com/challenges/word-order
https://www.hackerrank.com/challenges/words-score
https://www.hackerrank.com/challenges/write-a-function
https://www.hackerrank.com/challenges/xml-1-find-the-score
https://www.hackerrank.com/challenges/xml2-find-the-maximum-depth
https://www.hackerrank.com/challenges/zipped
