https://www.hackerrank.com/challenges/basics-of-sets-and-relational-algebra-1
https://www.hackerrank.com/challenges/basics-of-sets-and-relational-algebra-2
https://www.hackerrank.com/challenges/basics-of-sets-and-relational-algebra-3
https://www.hackerrank.com/challenges/basics-of-sets-and-relational-algebra-4
https://www.hackerrank.com/challenges/basics-of-sets-and-relational-algebra-5
https://www.hackerrank.com/challenges/basics-of-sets-and-relational-algebra-6
https://www.hackerrank.com/challenges/basics-of-sets-and-relational-algebra-7
https://www.hackerrank.com/challenges/bookmarks
https://www.hackerrank.com/challenges/database-normalization-10
https://www.hackerrank.com/challenges/database-normalization-1-1nf
https://www.hackerrank.com/challenges/database-normalization-123nf
https://www.hackerrank.com/challenges/database-normalization-3
https://www.hackerrank.com/challenges/database-normalization-4
https://www.hackerrank.com/challenges/database-normalization-5
https://www.hackerrank.com/challenges/database-normalization-6
https://www.hackerrank.com/challenges/database-normalization-7
https://www.hackerrank.com/challenges/database-normalization-8
https://www.hackerrank.com/challenges/database-normalization-9
https://www.hackerrank.com/challenges/database-query-languages
https://www.hackerrank.com/challenges/databases-differences
https://www.hackerrank.com/challenges/databases-keys
https://www.hackerrank.com/challenges/databases-natural-joins
https://www.hackerrank.com/challenges/databases-relational-calculus
https://www.hackerrank.com/challenges/indexes-1
https://www.hackerrank.com/challenges/indexes-2
https://www.hackerrank.com/challenges/indexes-3
https://www.hackerrank.com/challenges/indexes-4
https://www.hackerrank.com/challenges/map-reduce-advanced-count-number-of-friends
https://www.hackerrank.com/challenges/map-reduce-advanced-matrix-multiplication
https://www.hackerrank.com/challenges/map-reduce-advanced-relational-join
https://www.hackerrank.com/challenges/olap-cube-metadata
https://www.hackerrank.com/challenges/olap-names
https://www.hackerrank.com/challenges/olap-operations-1
https://www.hackerrank.com/challenges/olap-operations-2
https://www.hackerrank.com/challenges/olap-operation-types-2
https://www.hackerrank.com/challenges/olap-performance
https://www.hackerrank.com/challenges/procedural-language
https://www.hackerrank.com/challenges/querying-xml-datastores-with-xpath-1
https://www.hackerrank.com/challenges/querying-xml-datastores-with-xpath-10
https://www.hackerrank.com/challenges/querying-xml-datastores-with-xpath-11
https://www.hackerrank.com/challenges/querying-xml-datastores-with-xpath-1-1
https://www.hackerrank.com/challenges/querying-xml-datastores-with-xpath-1-4
https://www.hackerrank.com/challenges/querying-xml-datastores-with-xpath-3
https://www.hackerrank.com/challenges/querying-xml-datastores-with-xpath-4
https://www.hackerrank.com/challenges/querying-xml-datastores-with-xpath-6
https://www.hackerrank.com/challenges/querying-xml-datastores-with-xpath-7
https://www.hackerrank.com/challenges/querying-xml-datastores-with-xpath-8
https://www.hackerrank.com/challenges/querying-xml-datastores-with-xpath-9
https://www.hackerrank.com/challenges/relational-algebra-3
https://www.hackerrank.com/challenges/relational-algebra-4
https://www.hackerrank.com/challenges/relations-1
https://www.hackerrank.com/challenges/relations-2
https://www.hackerrank.com/challenges/the-total-view
