https://www.hackerrank.com/challenges/awk-1
https://www.hackerrank.com/challenges/awk-2
https://www.hackerrank.com/challenges/awk-3
https://www.hackerrank.com/challenges/awk-4
https://www.hackerrank.com/challenges/bash-tutorials---a-personalized-echo
https://www.hackerrank.com/challenges/bash-tutorials---arithmetic-operations
https://www.hackerrank.com/challenges/bash-tutorials---comparing-numbers
https://www.hackerrank.com/challenges/bash-tutorials---compute-the-average
https://www.hackerrank.com/challenges/bash-tutorials-concatenate-an-array-with-itself
https://www.hackerrank.com/challenges/bash-tutorials-count-the-number-of-elements-in-an-array
https://www.hackerrank.com/challenges/bash-tutorials-display-the-third-element-of-an-array
https://www.hackerrank.com/challenges/bash-tutorials-filter-an-array-with-patterns
https://www.hackerrank.com/challenges/bash-tutorials---getting-started-with-conditionals
https://www.hackerrank.com/challenges/bash-tutorials-lets-echo
https://www.hackerrank.com/challenges/bash-tutorials---looping-and-skipping
https://www.hackerrank.com/challenges/bash-tutorials---looping-with-numbers
https://www.hackerrank.com/challenges/bash-tutorials---more-on-conditionals
https://www.hackerrank.com/challenges/bash-tutorials-read-in-an-array
https://www.hackerrank.com/challenges/bash-tutorials-remove-the-first-capital-letter-from-each-array-element
https://www.hackerrank.com/challenges/bash-tutorials-slice-an-array
https://www.hackerrank.com/challenges/bash-tutorials---the-world-of-numbers
https://www.hackerrank.com/challenges/bookmarks
https://www.hackerrank.com/challenges/fractal-trees-all
https://www.hackerrank.com/challenges/lonely-integer-2
https://www.hackerrank.com/challenges/paste-1
https://www.hackerrank.com/challenges/paste-2
https://www.hackerrank.com/challenges/paste-3
https://www.hackerrank.com/challenges/paste-4
https://www.hackerrank.com/challenges/sed-command-4
https://www.hackerrank.com/challenges/sed-command-5
https://www.hackerrank.com/challenges/text-processing-cut-1
https://www.hackerrank.com/challenges/text-processing-cut-2
https://www.hackerrank.com/challenges/text-processing-cut-3
https://www.hackerrank.com/challenges/text-processing-cut-4
https://www.hackerrank.com/challenges/text-processing-cut-5
https://www.hackerrank.com/challenges/text-processing-cut-6
https://www.hackerrank.com/challenges/text-processing-cut-7
https://www.hackerrank.com/challenges/text-processing-cut-8
https://www.hackerrank.com/challenges/text-processing-cut-9
https://www.hackerrank.com/challenges/text-processing-head-1
https://www.hackerrank.com/challenges/text-processing-head-2
https://www.hackerrank.com/challenges/text-processing-in-linux-the-grep-command-1
https://www.hackerrank.com/challenges/text-processing-in-linux-the-grep-command-2
https://www.hackerrank.com/challenges/text-processing-in-linux-the-grep-command-3
https://www.hackerrank.com/challenges/text-processing-in-linux-the-grep-command-4
https://www.hackerrank.com/challenges/text-processing-in-linux-the-grep-command-5
https://www.hackerrank.com/challenges/text-processing-in-linux---the-middle-of-a-text-file
https://www.hackerrank.com/challenges/text-processing-in-linux-the-sed-command-1
https://www.hackerrank.com/challenges/text-processing-in-linux-the-sed-command-2
https://www.hackerrank.com/challenges/text-processing-in-linux-the-sed-command-3
https://www.hackerrank.com/challenges/text-processing-in-linux-the-uniq-command-1
https://www.hackerrank.com/challenges/text-processing-in-linux-the-uniq-command-2
https://www.hackerrank.com/challenges/text-processing-in-linux-the-uniq-command-3
https://www.hackerrank.com/challenges/text-processing-in-linux-the-uniq-command-4
https://www.hackerrank.com/challenges/text-processing-sort-1
https://www.hackerrank.com/challenges/text-processing-sort-2
https://www.hackerrank.com/challenges/text-processing-sort-3
https://www.hackerrank.com/challenges/text-processing-sort-4
https://www.hackerrank.com/challenges/text-processing-sort-5
https://www.hackerrank.com/challenges/text-processing-sort-6
https://www.hackerrank.com/challenges/text-processing-sort-7
https://www.hackerrank.com/challenges/text-processing-tail-1
https://www.hackerrank.com/challenges/text-processing-tail-2
https://www.hackerrank.com/challenges/text-processing-tr-1
https://www.hackerrank.com/challenges/text-processing-tr-2
https://www.hackerrank.com/challenges/text-processing-tr-3
